import asyncio
import importlib
import json
import logging
import os
import random

from google.adk.agents import LlmAgent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.adk.tools import AgentTool
from google.genai import types

logger = logging.getLogger(__name__)


def pprint_events(events):
    """Pretty print of events generated by ADK runner"""
    output = ''
    for _, event in enumerate(events):
        try:
            agent_res = json.loads(
                event.content.model_dump_json(indent=2, exclude_none=True)
            )
            output += json.dumps(agent_res) + '\n'
        except AttributeError as e:
            logger.error(f'Error parsing event content: {e}')
            continue
    return output


async def caller_factory(root_agent):
    """create a pre-configured agent caller.

    Args:
        root_agent: The ADK agent to handle conversations

    Returns:
        A function that takes a query string and returns agent response events.
    """
    user_id = 'User12345'
    app_name = 'App12345'

    session_service = InMemorySessionService()  #  to manage conversation sessions
    suffix = random.randint(100000, 999999)
    session_id = f'{app_name}-{user_id}-{suffix}'
    session = await session_service.create_session(
        app_name=app_name, user_id=user_id, session_id=session_id
    )
    runner = Runner(
        agent=root_agent, app_name=app_name, session_service=session_service
    )  # Create a Runner instance that will execute the agent

    def _call(query):
        content = types.Content(role='user', parts=[types.Part(text=query)])
        events = runner.run(
            user_id=session.user_id, session_id=session.id, new_message=content
        )
        return events

    return _call


async def run_agent_prompt(query, agent):
    try:
        caller = await caller_factory(agent)
        events_iterator = caller(query)
        return list(events_iterator)  # Consume the iterator to get all events
    except Exception:
        return {'status': 'error', 'message': 'An unexpected error occurred.'}


current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(current_dir)


def get_agents():
    """Get agents based on the current folder structure."""
    return {
        'status': 'success',
        'agents': [
            x
            for x in os.listdir(project_root)
            if x.startswith('0') and os.path.isdir(os.path.join(project_root, x))
        ],
    }


async def test_agent(agent_dir: str):
    """Test an individual agent based on the agent directory"""
    logger.info('Testing agent: %s', agent_dir)
    output = {'agent': agent_dir, 'outcome': None}
    try:
        module_name = f'{agent_dir}.agent'
        agent_module = importlib.import_module(module_name)
        events = await run_agent_prompt('Hello', agent_module.root_agent)
        output['outcome'] = pprint_events(events)
    except ModuleNotFoundError:
        return {
            'status': 'error',
            'message': f"Agent module for directory '{agent_dir}' not found.",
        }
    logger.info(output)
    return output


analyse_results = LlmAgent(
    name='analyse_agent',
    model='gemini-2.5-flash',
    description='An Agent that is able to analyse a Google ADK run',
    instruction=(
        'Analyse the result of the agent run'
        'and output if there was any error with the execution with emojis.'
        'Output for each agent the agent name and an emoji displaying the status.'
        'For failed agents, output an error description.'
    ),
)

root_agent = LlmAgent(
    name='test_agent',
    model='gemini-2.5-flash',
    description='an agent that executes tests',
    instruction=(
        'Use the tool `get_agents` to get a list of agents to test.'
        'For each of the agents in the list, execute `test_agent` in parallel and'
        'after all executions are finished, use the tool `analyse_results` to check'
        'the outcome of the agent.'
        'Output for each agent the agent name and an emoji displaying the status'
        'For failed agents, output an error description.'
    ),
    tools=[get_agents, test_agent, AgentTool(analyse_results)],
)
